export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const CLEAR_CURRENT_USER_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const SET_CURRENT_COMPANY= 'SET_CURRENT_COMPANY';
export const COMPANY_PROFILE_LOADING = 'COMPANY_PROFILE_LOADING';
export const CLEAR_CURRENT_COMPANY_PROFILE = 'CLEAR_CURRENT_COMPANY_PROFILE';



export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';


export const COMPANY_REGISTER_SUCCESS = 'COMPANY_REGISTER_SUCCESS';
export const COMPANY_LOADED = 'COMPANY_LOADED';
export const COMPANY_LOGIN_SUCCESS = 'COMPANY_LOGIN_SUCCESS';
export const COMPANY_AUTH_ERROR = 'COMPANY_AUTH_ERROR';
export const COMPANY_REGISTER_FAIL = 'COMPANY_REGISTER_FAIL';
export const COMPANY_LOGIN_FAIL = 'COMPANY_LOGIN_FAIL';
export const COMPANY_LOGOUT = 'COMPANY_LOGOUT';


export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILES = 'GET_USER_PROFILES';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const USER_ACCOUNT_DELETED = 'USER_ACCOUNT_DELETED';


export const GET_COMPANY_PROFILE = 'GET_COMPANY_PROFILE';
export const GET_COMPANY_PROFILES = 'GET_COMPANY_PROFILES';
export const COMPANY_PROFILE_ERROR = 'COMPANY_PROFILE_ERROR';
export const CLEAR_COMPANY_PROFILE = 'CLEAR_COMPANY_PROFILE';
export const UPDATE_COMPANY_PROFILE = 'UPDATE_COMPANY_PROFILE';
export const COMPANY_ACCOUNT_DELETED = 'COMPANY_ACCOUNT_DELETED';


export const POST_ERROR = 'POST_ERROR';
export const GET_POSTS = 'GET_POSTS';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';